#!/bin/sh

mkdir -p $1
mkdir -p $1/docs
mkdir -p $1/src
mkdir -p $1/src/g_doom
mkdir -p $1/src/g_heretic
mkdir -p $1/src/g_hexen
mkdir -p $1/src/g_raven
mkdir -p $1/src/g_shared
mkdir -p $1/src/linux
mkdir -p $1/src/win32
mkdir -p $1/src/fmodsound

function yescr()
{
	if [ $2 -nt $1 -o ! -f $1 ]; then
		util/addremcr a $2 $1
		touch -r $2 $1
echo $2 $1
	fi
}

yescr $1/docs/zdoom.txt README
yescr $1/INSTALL INSTALL
yescr $1/Makefile Makefile
yescr $1/docs/classes.txt docs/Classes
yescr $1/docs/doomlic.txt docs/DoomLicense
yescr $1/docs/colors.txt docs/colors.txt
yescr $1/docs/commands.txt docs/commands.txt
yescr $1/docs/history.txt docs/history.txt
yescr $1/docs/rh-log.txt docs/rh-log.txt
yescr $1/docs/notes.txt docs/notes.txt
yescr $1/docs/README.Carmack docs/README.Carmack
yescr $1/docs/README.asm docs/README.asm
yescr $1/docs/README.gl docs/README.gl

for i in src/*.cpp src/*.h src/*.nas src/g_doom/* src/g_heretic/* src/g_hexen/* src/g_raven/* src/g_shared/* src/fmodsound/* src/Linux/*; do
	yescr $1/$i $i
done

for i in src/win32/* src/*.ds?; do
	if [ $i -ot $mydir/$i -o ! -f $i ]; then
		cp $i $1/$i
		touch -r $i $1/$i
	fi
done
